CREATE TABLE POKEMON
(
ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(255),
TIPO VARCHAR(255)
);

INSERT INTO POKEMON VALUES (1,'PIKACHU','RATA');
INSERT INTO POKEMON VALUES (2,'MEWTWO','GATO');
INSERT INTO POKEMON VALUES (3,'CHARMELEON','CAMALEON');
INSERT INTO POKEMON VALUES (4,'CHARIZARD','LAGARTO');